# Generated by Django 3.1.5 on 2021-01-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210119_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default='', verbose_name='date published'),
        ),
    ]
