# Generated by Django 3.1.5 on 2021-01-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210119_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
